### ISSUE TITLE
[Feature Request]: Deployment Clean Up

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#208]
### Implementation ideas

See if we can consolidate the deploy and previews into a single action. 

```yml
name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: npm ci
      - name: Build with VitePress
        run: npm run docs:build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # Assuming the VitePress dist directory is docs/.vitepress/dist
          folder: docs/.vitepress/dist
          branch: gh-pages  # The branch to deploy to, typically gh-pages
          clean: true  # This will clean old files in the deployment branch
```
